### ISSUE TITLE
Error in generic node Convert to R

### ISSUE THREAD

**Issue by stoeter** [knime-mpicbg/knime-scripting#101]
Generic nodes dont work:

“ERROR R Plot 2:792 Unable to clone input data at port 1 (existing R workspace): org.rosuda.REngine.REXPGenericVector cannot be cast to org.rosuda.REngine.REXPString”.

See this KNIME forum post:
https://forum.knime.com/t/rserve-hangs-with-r-plot-node/16941

**Comment by niederle** [comment]
The problem is caused by an old RServe-package (version 1.7.x) on R-side. Unfortunately, Rserve package binaries are only available until version 1.7.x. Version 1.8 can be build from source but binaries are not available.
