### ISSUE TITLE
python nodes should use pandas library

### ISSUE THREAD

**Issue by niederle** [knime-mpicbg/knime-scripting#19]
kIn should be a data frame object of the pandas library as these objects are much better for data manipulation

**Comment by damoser** [comment]
You can easily transfer the kIn-dict to a pandas dataframe using

```
df = pandas.DataFrame(data=kIn)
```

However, I share your opinion. If pandas is available it should be used.
Maybe #23 is a start. I'll see what i can do.

**Comment by damoser** [comment]
Changing kIn to a pandas DataFrame could break backwards-compatibility. Therefore I suggest to mark the current nodes as deprecated (e.g. "Python Snippet (deprecated)") and introduce a new set of nodes with a different plugin id which use pandas.
What's your opinion? I would be happy to make those changes if you agree with me.
