### ISSUE TITLE
open in python should support linux

### ISSUE THREAD

**Issue by niederle** [knime-mpicbg/knime-scripting#29]
linux is reported as unsupported platform.
is there any reason, why?

**Comment by fmeyenhofer** [comment]
no, there shouldn't be. The python server at the CBG was a Linux server (at least when I was working there). So I don't know who and why this reported. Is there more information?

**Comment by niederle** [comment]
no, there is no further documentation at the source code.
look at line 84:
https://github.com/knime-mpicbg/knime-scripting/blob/develop/de.mpicbg.knime.scripting.python/src/de/mpicbg/knime/scripting/python/OpenInPythonNodeModel.java

**Comment by fmeyenhofer** [comment]
ok right. The server runs in linux (there is no script for windows yet) but the node (OpenInPython) does not support linux (should read the title of the issue ;)

This might help
http://stackoverflow.com/questions/9952680/firing-a-command-through-terminal-in-ubuntu-using-java-runtime-exec
.. at least for Ubuntu

together with 

```
System.getProperty("os.name");
```

... this should pretty much be the solution
will go after this asap. (Have already a Ubuntu VM for testing...)
