### ISSUE TITLE
text encoding problems with non-ASCII characters typed into the code pane of R nodes

### ISSUE THREAD

**Issue by g3o2** [knime-mpicbg/knime-scripting#78]
When typing non-ASCII text (e.g. a French axis label in e.g. ggplot2) in the code pane of an R View node, I've observed that when the image is returned back to KNIME, the text input via the code pane is returned with encoding problems. Typical French non-ASCII characters such as é or à are sent back to KNIME as @ or other equivalents in a different code page. The same encoding problems occur with the German ä ö ü. 
In other R nodes, searches via code containing such characters are consequently impossible - in the code pane, a search for "personnes occupées" would not yield any hits even if the text string is present in a given table sent to R. See the attached example: [text_encoding_problems_code_pane.zip](https://github.com/knime-mpicbg/knime-scripting/files/222126/text_encoding_problems_code_pane.zip)

There is no such behaviour with text sent to R and back via a table itself - the problems stem from the text entered via the code pane only. In R, the same code would run without any text encoding problems, so it appears to originate from KNIME's R nodes' code pane. The text encoding preferences in both R and KNIME are set to UTF-8 in my configuration. The behaviour is reproducible on Windows (cp1252) but also on Mac OS X (utf-8).

**Comment by g3o2** [comment]
closed for apparent lack of interest, signalled via the KNIME forum instead

**Comment by niederle** [comment]
I should have checked the issue earlier - sorry.
Anyhow, this github repo is from the community scripting extension. Your bug appears in the R scripting integration from KNIME itself. So the forum is indeed the place to put your report. I cannot help.
