### ISSUE TITLE
Adding templates in the preferences fails silently when rgg syntax error

### ISSUE THREAD

**Issue by fmeyenhofer** [knime-mpicbg/knime-scripting#84]
When trying to add a template, that has certain syntax errors (in my case it was a missing carrage return between ###### and <rgg>) then the file won't be added to the table. The file dialog closes, but nothing happens. The same if the url is typed by hand. 
An error message would help...

**Comment by niederle** [comment]
I cannot reproduce the syntax-error problem. Could you provide a file as example?
"Typing URL by hand": is that just a problem with files having syntax errors? If not, I cannot confirm.

**Comment by fmeyenhofer** [comment]
After trying again, there were dialogs indicating syntax-errors if there was an error in the URL and also if the there were RGG syntax errors in the template file. I couldn't reproduce the error anymore. So let's close this for now.
