### ISSUE TITLE
Cannot import data to matlab

### ISSUE THREAD

**Issue by jochenkrattenmacher** [knime-mpicbg/knime-scripting#91]
Hello!

When I try to open data with matlab (a simple table with one column, which has a header "x" and a dozen numerical values), a matlab error occurs:

`Error using cell
Size vector should be a row vector with real elements.
Error in hashmaputils>loadhashmap (line 158)
        vector = cell(vector);
Error in hashmaputils (line 45)
    [kIn, columnNames] = loadhashmap(input.filePath, input.data); `

When I catch the error and try to view the value of the 'vector' variable, I see the following:
`Variable "vector" is inaccessible. When a variable appears on both sides of an
assignment statement, the variable may become temporarily unavailable during
processing. `

I am using Matlab R2016b and Knime 3.5.3 (downloaded the matlab scripting extension within the GUI).

**Comment by fmeyenhofer** [comment]
c6a2707d0413c95563be779a9c86d5be7a1213e9
